### PR TITLE
Convert app to kotlin

### PR DESCRIPTION
**Pull request by fadeltd**
Resolve issue #14 

I use kotlin-android-extensions to simplify most view assignment
I also updated to the latest version of sdk, androidx and gradle version

### CODE REVIEW

**Comment by robertoduessmann** [comment]
Thanks a lot @fadeltd , really appreciate it! :tada: 
Sorry for the delay was quite busy last weeks, I'm checking it now.
I just saw there is a conflict in MainActivity.java, I think I merged something in the meantime, could you please just have a look on it?
Thanks again :rocket:

**Comment by fadeltd** [comment]
> Thanks a lot @fadeltd , really appreciate it! 🎉
> Sorry for the delay was quite busy last weeks, I'm checking it now.
> I just saw there is a conflict in MainActivity.java, I think I merged something in the meantime, could you please just have a look on it?
> Thanks again 🚀

Done

**Review by robertoduessmann — APPROVED** [review]

**Comment by robertoduessmann** [comment]
Thanks a lot for the contribution @fadeltd :rocket:

**Comment by robertoduessmann** [comment]
closes https://github.com/robertoduessmann/churrascometro/issues/14

**Pull request merged**
